name_or_path: google/gemma-7b
tokenizer_name_or_path: null
archive: null
block_name: null

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float32

use_lora: True
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.0
lora_target_modules:
  - q_proj
  - o_proj
  - k_proj
  - v_proj
  - gate_proj
  - up_proj
  - down_proj 